### ISSUE TITLE
Make URLs redirects work

### ISSUE THREAD

**Issue by fredddier** [fredddier/atm#6]
If a not logged in user writes a task and clicks on the Log In button, the user must be redirected to the Makerlog auth flow, after granting permission he then is redirected back to the application and the last text he wrote must be prefilled in the input. Then after successfully logging in that task the `localStorage` must be erased. 

Actually after the user is redirected back to the app, the previous text he wrote is missing, need to fix this.

Use local `localStorage` or any other alternative.

**Comment by curranlipsett** [comment]
I'll take a shot at this!

**Comment by curranlipsett** [comment]
PR - https://github.com/fredddier/atm/pull/8

**Comment by fredddier** [comment]
Closed by #8
